core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("vcards.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import RegisterView, logout_view

app_name = "users"

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

vcards/urls.py
from django.urls import path

from .views import (
    DownloadVCardFileView,
    MultiStepFormView,
    VCardCreateView,
    VCardDetailView,
)

app_name = "vcards"

urlpatterns = [
    path("create/", VCardCreateView.as_view(), name="create_vcard"),
    path("detail/<int:pk>/", VCardDetailView.as_view(), name="vcard_detail"),
    path("<str:unique_url>/", MultiStepFormView.as_view(), name="multi_step_form"),
    path("download-vcard/<str:unique_url>/", DownloadVCardFileView.as_view(), name="download_vcard"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/cerulean/bootstrap.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'vcards:create_vcard' %}">RAE Task</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="container mt-4">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>